In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt 

In [12]:
cd data stuff

/home/ashu/Desktop/data stuff


In [13]:
dataset = pd.read_csv("7.1 Social_Network_Ads.csv.csv")

In [14]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [15]:
x = dataset.iloc[:,[2,3]].values

In [16]:
y = dataset.iloc[:,[4]].values

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train , x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

In [34]:
x_train.shape

(300, 2)

In [35]:
y_train.shape

(300, 1)

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
sc = StandardScaler()

In [42]:
x_train = sc.fit_transform(x_train)

In [43]:
x_test =sc.transform(x_test)

In [44]:
x_train

array([[-1.08893369,  0.04732215],
       [-0.71664866, -0.24240529],
       [ 0.21406389, -0.67699646],
       [ 0.86556267,  1.23520466],
       [-1.18200494,  0.25013136],
       [ 0.86556267, -1.37234232],
       [ 1.14477644,  0.51088606],
       [ 0.77249142,  0.33704959],
       [ 0.02792138,  1.20623192],
       [ 0.12099263, -0.82186018],
       [-1.64736122,  0.10526764],
       [-1.2750762 ,  0.5398588 ],
       [-0.90279118, -0.32932353],
       [ 0.12099263,  1.49595936],
       [-1.55428996, -0.06856883],
       [ 0.4002064 , -0.47418725],
       [ 1.4239902 ,  0.04732215],
       [-1.08893369,  0.45294057],
       [-0.06514988,  1.93055052],
       [ 1.05170518, -0.15548706],
       [-0.62357741, -1.51720604],
       [-1.64736122,  0.33704959],
       [ 1.23784769, -1.37234232],
       [-0.53050615,  0.85855899],
       [ 0.86556267, -0.79288743],
       [-1.18200494,  0.56883154],
       [-0.25129239,  0.51088606],
       [ 0.77249142, -1.40131506],
       [-0.99586243,

In [45]:
x_test

array([[ 0.86556267,  2.13335973],
       [-0.25129239, -0.30035078],
       [ 0.12099263,  0.0183494 ],
       [-0.34436364,  1.29315015],
       [-1.08893369, -0.79288743],
       [ 1.05170518, -1.22747859],
       [ 0.02792138, -0.4452145 ],
       [-0.71664866,  1.06136819],
       [ 0.4002064 ,  2.27822345],
       [ 0.12099263, -0.32932353],
       [-0.06514988,  0.0183494 ],
       [ 0.58634891, -0.90877841],
       [ 0.95863393, -1.08261487],
       [-0.15822113, -1.08261487],
       [-0.99586243, -0.38726901],
       [-0.25129239, -0.93775115],
       [ 1.88934648, -0.67699646],
       [ 2.07548899,  0.91650447],
       [-1.2750762 , -0.4452145 ],
       [-1.18200494,  0.48191331],
       [-1.64736122,  0.33704959],
       [ 1.33091895,  0.56883154],
       [-0.53050615,  1.87260503],
       [-1.18200494,  0.2791041 ],
       [ 0.21406389,  1.06136819],
       [-0.25129239,  0.59780429],
       [ 0.67942016,  0.25013136],
       [-0.06514988, -0.50315999],
       [ 0.86556267,

In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski')

In [53]:
classifier.fit(x_train, y_train)

/home/ashu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [59]:
y_pred = classifier.predict(x_test)

In [60]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [58]:
y_test

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
cm = confusion_matrix(y_test, y_pred)

In [63]:
cm

array([[60,  5],
       [ 2, 33]])

In [66]:
(60+33)/(60+5+2+33)  # here accuracy is 93%.

0.93